//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.MiniPortal.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public Label()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public long labelId { get; set; }
        public string name { get; set; }
        public int commentsNum { get; set; }


        public virtual ICollection<Comment> Comments { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	//  like a hash table. It uses the Josh Bloch implementation from "Effective Java"
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + labelId.GetHashCode();
    			hash = hash * multiplier + (name == null ? 0 : name.GetHashCode());
                hash = hash * multiplier + commentsNum.GetHashCode();

                return hash;
    	    }
    
    	}
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
    	public override bool Equals(object obj)
    	{
    	    Label target = (Label)obj;
    
    		return true
               &&  (this.labelId == target.labelId )       
               &&  (this.name == target.name )
                && (this.commentsNum == target.commentsNum)
               ;
    
        }
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strLabel = new StringBuilder();
    
    		strLabel.Append("[ ");
           strLabel.Append(" labelId = " + labelId + " | " );       
           strLabel.Append(" name = " + name + " | " );
            strLabel.Append(" commentsNum = " + commentsNum + " | ");
            strLabel.Append("] ");    
    
    		return strLabel.ToString();
        }
    
    
    }
}
